# Generated by Django 5.2.6 on 2025-10-01 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('AHORRO', 'Cuenta de Ahorro'), ('CORRIENTE', 'Cuenta Corriente'), ('PLAZO', 'Cuenta a Plazo Fijo')], max_length=10)),
                ('moneda', models.CharField(choices=[('SOLES', 'Soles'), ('DOLARES', 'Dólares')], max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('CERRADA', 'Cerrada'), ('EMBARGADA', 'Embargada')], default='ACTIVA', max_length=10)),
                ('monto_sobregiro', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo de sobregiro permitido', max_digits=15)),
                ('monto_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('plazo_meses', models.IntegerField(blank=True, help_text='Plazo en meses', null=True)),
                ('tasa_interes_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés mensual en porcentaje', max_digits=5, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_embargado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('embargo_total', models.BooleanField(default=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='clientes.cliente')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_aperturadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuentas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Embargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oficio', models.CharField(max_length=50, unique=True)),
                ('juzgado', models.CharField(max_length=200)),
                ('monto_embargado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('es_total', models.BooleanField(default=False)),
                ('fecha_embargo', models.DateTimeField(auto_now_add=True)),
                ('fecha_levantamiento', models.DateTimeField(blank=True, null=True)),
                ('esta_vigente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embargos', to='cuentas.cuenta')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embargos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Embargo',
                'verbose_name_plural': 'Embargos',
                'db_table': 'embargos',
                'ordering': ['-fecha_embargo'],
            },
        ),
    ]
