# Generated by Django 5.2.6 on 2025-10-01 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA_ENVIADA', 'Transferencia Enviada'), ('TRANSFERENCIA_RECIBIDA', 'Transferencia Recibida'), ('APERTURA', 'Apertura de Cuenta'), ('CIERRE', 'Cierre de Cuenta'), ('CANCELACION_PLAZO', 'Cancelación de Plazo Fijo'), ('RENOVACION_PLAZO', 'Renovación de Plazo Fijo'), ('INTERES_PLAZO', 'Interés de Plazo Fijo'), ('EMBARGO', 'Embargo'), ('DESEMBARGO', 'Levantamiento de Embargo')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('clave_autorizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('origen_fondos', models.TextField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cuentas.cuenta')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recibidos', to='cuentas.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('clave_autorizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('origen_fondos', models.TextField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='cuentas.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos_realizados', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposito', to='operaciones.movimiento')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'db_table': 'depositos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='OperacionPlazoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('CANCELACION', 'Cancelación'), ('RENOVACION', 'Renovación')], max_length=15)),
                ('monto_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interes_generado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nuevo_plazo_meses', models.IntegerField(blank=True, null=True)),
                ('nueva_tasa_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_plazo', to='cuentas.cuenta')),
                ('nueva_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacion_desde', to='cuentas.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_plazo_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación de Plazo Fijo',
                'verbose_name_plural': 'Operaciones de Plazo Fijo',
                'db_table': 'operaciones_plazo_fijo',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros', to='cuentas.cuenta')),
                ('movimiento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiro', to='operaciones.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'db_table': 'retiros',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='cuentas.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='cuentas.cuenta')),
                ('movimiento_destino', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_destino', to='operaciones.movimiento')),
                ('movimiento_origen', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_origen', to='operaciones.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'db_table': 'transferencias',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['-fecha_hora'], name='movimientos_fecha_h_266165_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['cuenta', '-fecha_hora'], name='movimientos_cuenta__42fff1_idx'),
        ),
    ]
